rom_config: ../../extract/config.yaml
build_path: ../../build
delinks_path: ../../build/delinks
main_module:
  name: main
  object: ../../build/build/arm9.bin
  hash: 6a78b660eb55dcda
  delinks: delinks.txt
  symbols: symbols.txt
  relocations: relocs.txt
autoloads:
  - kind: Itcm
    name: itcm
    object: ../../build/build/itcm.bin
    hash: 702c81c65afe0e79
    delinks: itcm/delinks.txt
    symbols: itcm/symbols.txt
    relocations: itcm/relocs.txt
  - kind: Dtcm
    name: dtcm
    object: ../../build/build/dtcm.bin
    hash: e1f0db28accd3af3
    delinks: dtcm/delinks.txt
    symbols: dtcm/symbols.txt
    relocations: dtcm/relocs.txt
overlays:
  []
