#!/usr/bin/env python3
"""Translate the mwldarm linker command file generated by `dsd lcf` into a GNU ld script.

dsd computes the correct link order for every translation unit and writes it as
an LCF for Metrowerks' proprietary mwldarm linker. This project links with the
free GNU toolchain (arm-none-eabi-ld) instead, so we convert the LCF:

  ALIGNALL(4);            -> every input section is preceded by `. = ALIGN(4);`
  foo.o(.text)            -> "path/to/foo.o"(.text)
  WRITEW(0);              -> LONG(0);
  EXCEPTION               -> the .exceptix input sections of every object
  .bss / BSS_START blocks -> moved into a NOLOAD output section, so that
                             objcopy -O binary only emits the loadable bytes

Usage: lcf2ld.py <in.lcf> <objects.txt> <out.ld>
"""
import re
import sys

src = open(sys.argv[1]).read()
# map object basenames used in the LCF to the paths passed to the linker
obj_paths = {}
for line in open(sys.argv[2]):
    path = line.strip().strip('"')
    if path:
        obj_paths[path.replace("\\", "/").split("/")[-1]] = path


def objref(name):
    return '"' + obj_paths.get(name, name) + '"'


# ---------------------------------------------------------------- MEMORY
mem = {}
for name, origin in re.findall(r"^\s*(\w+)\s*:\s*ORIGIN\s*=\s*(0x[0-9a-fA-F]+)", src, re.M):
    mem[name] = int(origin, 16)

# symbols assigned at top of SECTIONS (e.g. __DTCM_LO)
sections_head = src[src.index("SECTIONS"):]
sections_head = sections_head[:re.search(r"^\s*\.\w+\s*:\s*\{", sections_head, re.M).start()]
top_syms = re.findall(r"^\s*(__\w+)\s*=\s*([^;]+);", sections_head, re.M)

# ---------------------------------------------------------------- SECTIONS
blocks = re.findall(r"^\s*(\.\w+)\s*:\s*\{(.*?)^\s*\}\s*>\s*(\w+)", src, re.M | re.S)

out = []
out.append("/* Generated by tools/lcf2ld.py from the dsd LCF - do not edit */")
out.append("OUTPUT_ARCH(arm)")
out.append("ENTRY(Entry)")
out.append("MEMORY {")
for name, origin in mem.items():
    if name == "SPACE":
        continue
    out.append(f"    {name} (rwx) : ORIGIN = {origin:#010x}, LENGTH = 0x400000")
out.append("}")
out.append("SECTIONS {")

for blk_name, body, region in blocks:
    lines = [l.strip() for l in body.splitlines() if l.strip()]
    align_all = any(l.startswith("ALIGNALL") for l in lines)

    # collect objects mentioned anywhere in this block (for EXCEPTION)
    objs_in_block = []
    for l in lines:
        m = re.match(r"^([^\s(]+\.o)\((\.\w+)\)$", l)
        if m and m.group(1) not in objs_in_block:
            objs_in_block.append(m.group(1))

    load, bss = [], []
    cur = load
    for l in lines:
        if l.startswith("ALIGNALL"):
            continue
        # BSS part starts at the "*_BSS_START = ." marker; the alignment line
        # right before it belongs with it.
        if re.match(r"^\w+_BSS_START\s*=\s*\.;", l):
            if cur is load and load and load[-1].startswith(". = ALIGN"):
                bss.append(load.pop())
            cur = bss
        m = re.match(r"^([^\s(]+\.o)\((\.\w+)\)$", l)
        if m:
            if align_all:
                cur.append(". = ALIGN(4);")
            cur.append(f"{objref(m.group(1))}({m.group(2)})")
            continue
        if l.startswith("WRITEW("):
            cur.append("LONG(" + l[len("WRITEW("):].rstrip(";").rstrip(")") + ");")
            continue
        if l == "EXCEPTION":
            for o in objs_in_block:
                if align_all:
                    cur.append(". = ALIGN(4);")
                cur.append(f"{objref(o)}(.exceptix)")
            continue
        cur.append(l)

    # mwldarm names output sections after their memory region (ARM9, ITCM,
    # DTCM); `dsd rom config` looks them up by that name.
    out.append(f"    {region} : {{")
    out += ["        " + x for x in load]
    out.append(f"    }} > {region}")
    out.append(f"    {region}.bss (NOLOAD) : {{")
    out += ["        " + x for x in bss]
    out.append(f"    }} > {region}")

for sym, expr in top_syms:
    expr = expr.strip()
    expr = re.sub(r"ADDR\((ITCM|DTCM|ARM9)\)", lambda m: f"ADDR({m.group(1)})", expr)
    expr = re.sub(r"SIZEOF\((ITCM|DTCM|ARM9)\)", lambda m: f"SIZEOF({m.group(1)})", expr)
    if "SPACE" in expr:
        expr = "ADDR(ARM9.bss) + SIZEOF(ARM9.bss)"
    out.append(f"    {sym} = {expr};")

out.append("    /DISCARD/ : { *(.ARM.attributes) *(.comment) *(.note.GNU-stack) *(.ARM.exidx*) *(.ARM.extab*) }")
out.append("}")
open(sys.argv[3], "w").write("\n".join(out) + "\n")
