#!/usr/bin/env python3
"""Report decompilation progress: functions and code bytes covered by `complete` TUs.

Usage: progress.py [--markdown PROGRESS.md]
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

funcs = []
for line in open(os.path.join(ROOT, "config/arm9/symbols.txt")):
    m = re.match(r"(\S+) kind:function\(\w+,size=(0x[0-9a-f]+)[^)]*\) addr:(0x[0-9a-f]+)", line)
    if m:
        funcs.append((int(m.group(3), 16), int(m.group(2), 16), m.group(1)))

done_ranges, tus, tu_ranges = [], [], {}
cur, complete = None, False
for line in open(os.path.join(ROOT, "config/arm9/delinks.txt")):
    if re.match(r"^\S.*:\s*$", line):
        cur, complete = line.strip().rstrip(":"), False
        continue
    if cur and line.strip() == "complete":
        complete = True
        tus.append(cur)
    m = re.match(r"\s+\.text\s+start:(0x[0-9a-f]+) end:(0x[0-9a-f]+)", line)
    if cur and complete and m:
        done_ranges.append((int(m.group(1), 16), int(m.group(2), 16)))
        tu_ranges[cur] = done_ranges[-1]

done = [f for f in funcs if any(lo <= f[0] < hi for lo, hi in done_ranges)]
named = [f for f in funcs if not f[2].startswith("func_")]
total_bytes = sum(f[1] for f in funcs)
done_bytes = sum(f[1] for f in done)
def describe(t):
    src = os.path.join(ROOT, t)
    if os.path.exists(src):
        m = re.search(r"/\*\s*\n?\s*\*?\s*(.+?)\n", open(src).read())
        if m:
            return m.group(1).strip().rstrip(".")
    return ""


print(f"translation units decompiled : {len(tus)}")
for t in tus:
    print(f"    {t:<28}{describe(t)}")
print(f"functions decompiled         : {len(done)} / {len(funcs)} ({100 * len(done) / len(funcs):.2f}%)")
print(f"code bytes decompiled        : {done_bytes} / {total_bytes} ({100 * done_bytes / total_bytes:.2f}%)")
print(f"functions with real names    : {len(named)} / {len(funcs)}")

if "--markdown" in sys.argv:
    out = sys.argv[sys.argv.index("--markdown") + 1]
    lines = ["# Decompilation progress", "",
             "Generated by `python3 tools/progress.py --markdown PROGRESS.md`.", "",
             f"* Functions decompiled: **{len(done)} / {len(funcs)}** ({100 * len(done) / len(funcs):.2f}%)",
             f"* Code bytes decompiled: {done_bytes} / {total_bytes} ({100 * done_bytes / total_bytes:.2f}%)",
             f"* Functions with real names: {len(named)} / {len(funcs)}", ""]
    log = os.path.join(ROOT, "build", "difftest.log")
    if os.path.exists(log):
        tail = [l for l in open(log).read().splitlines() if l.strip()][-1]
        lines += [f"* Last differential test run: `{tail}`", ""]
    lines += ["| Translation unit | Address range | Functions | Contents |", "|---|---|---:|---|"]
    for t in sorted(tus, key=lambda t: tu_ranges.get(t, (0, 0))[0]):
        lo, hi = tu_ranges.get(t, (0, 0))
        n = len([f for f in funcs if lo <= f[0] < hi])
        lines.append(f"| `{t}` | `{lo:#010x}`-`{hi:#010x}` | {n} | {describe(t)} |")
    lines += ["", "Not decompiled on purpose: `0x02000000`-`0x02001930` (secure area, crt0 and",
              "hand-written assembly: a decompressor and audio filter routines with custom",
              "register conventions)."]
    open(out, "w").write("\n".join(lines) + "\n")
    print(f"wrote {out}")
