#!/usr/bin/env python3
"""Print the disassembly of one or more functions from asm/ (generated by `dsd dis`).

Usage: show.py <name-or-address> [...]
"""
import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
text = ""
for f in sorted(glob.glob(os.path.join(ROOT, "asm", "**", "*.s"), recursive=True)):
    text += open(f).read()

addr_to_name = {}
for line in open(os.path.join(ROOT, "config/arm9/symbols.txt")):
    m = re.match(r"(\S+) kind:function\S* addr:(0x[0-9a-f]+)", line)
    if m:
        addr_to_name[int(m.group(2), 16)] = m.group(1)

for q in sys.argv[1:]:
    name = q
    if re.match(r"^(0x)?[0-9a-fA-F]{8}$", q):
        name = addr_to_name.get(int(q, 16), q)
    m = re.search(r"^\s*(arm|thumb)_func_start " + re.escape(name) + r"\n(.*?)^\s*(arm|thumb)_func_end " + re.escape(name) + r"\n",
                  text, re.M | re.S)
    if not m:
        print(f"; {q}: not found")
        continue
    print(m.group(0))
